


## 예외처리
*Exception Handling*  

**프로그램 실행시 발생 가능한 예외를 대비하여 코드를 작성하는 것.**  
갑작스런 비정상 종료를 막고, 정상적인 실행 상태를 유지한다.

```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
            //try : 예외 발생 가능성이 있는 코드를 넣는다.
			int a = 22;
			int b = 0;
			System.out.println("a + b = " + (a + b));
			System.out.println("a - b = " + (a - b));
			System.out.println("a * b = " + (a * b));
			System.out.println("a / b = " + (a / b));
			//try문 내에서 예외가 발생하게 되면, 
			//발생 지점 이후의 코드는 실행되지 않는다.
			System.out.println("계산 완료!");

		} catch (Exception e) {
            //catch : 예외가 일어나면 실행되는 영역. 
			//예외 타입과 참조변수를 넣는다.
            //e는 발생하는 예외 객체를 가리킨다.

			//System.out.println("예외 메시지 : " + e.getMessage());
			System.err.println("예외 메시지 : " + e.getMessage());
			//System.out을 안 쓰고 System.err를 쓴 점에 주목해 달라.
            //err를 쓴 경우, 다른 에러 메시지처럼 콘솔에서 빨간색으로 출력된다.

            e.printStackTrace(); 
			//예외가 일어나면 추적(history)내용까지 출력. 디버깅할 때 많이 쓴다.
		}finally {//try-catch-finally
			//예외가 있든 없든 무조건 실행하는 구문이다.
			System.out.println("finally 실행");
		}
		
	}

}

```

- try catch 내부에 또다른 try catch를 작성할 수도 있다. 
  
&nbsp;  
### 예외 메시지 출력
- printStackTrace() : 예외 발생 당시의 호출스택에 있던 메서드 정보, 예외 메시지를 출력한다.
- getMessage() : 발생한 예외 클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

&nbsp;  
&nbsp;  
### 여러 개의 catch 블럭
- catch 블럭을 여러 개 만들 수도 있다.


```java

public class ExceptionEx1 {

	public static void main(String[] args) {
		try {

		} catch (Exception1 e1) {
            //특정 형태의 예외 Exception1이 발생하면 실행하는 코드.

			System.err.println("예외 메시지 : " + e.getMessage());

            e1.printStackTrace(); 
			
		} catch (Exception2 e2) {
			//첫 번째 catch 블록에서 감지된 예외가 없다면 아래 블록으로 내려온다.
			//또다른 형태의 예외 Exception2가 발생하면 실행하는 코드.
			e2.printStackTrace(); 
		}
	}
}

```
### 멀티 catch블럭 :   
JDK 1.7부터는 '|' 기호를 이용해   
한 블럭 내에 여러 타입의 예외를 포착할 수 있다.  
(이 때, |는 논리 연산자가 아닌 기호일 뿐이다.)

```java

public class ExceptionEx1 {

	public static void main(String[] args) {
		try {

		} catch (Exception1 | Exception2 e) {
            //Exception1 또는 Exception2가 발생하면 실행하는 코드.

			System.err.println("예외 메시지 : " + e.getMessage());

            e.printStackTrace(); 
			
		} 
	}
}

```
**사용 시의 제약**
- Exception1이 Exception2의 부모 클래스라면 컴파일 에러가 발생하는데,  
그럴 바에야 Exception1만 쓰면 되는 거고 쓸데없는 코드 중복이라 에러로 취급한다.  

- 참조변수 e로는 처리 대상이 되는 예외 클래스에 직접 접근할 수 없다.  
  둘 중 어느 유형에 해당하는 예외인지 알 수 없기 때문에,   
  e는 오직 두 클래스의 공통 부모 클래스에 속한 멤버만 접근 가능하다.

- 참조변수 e는 상수로 값을 변경할 수 없다.
여러 catch블럭이 하나의 참조변수를 공유하고 있기 때문이다.

```
다만 멀티블럭을 쓰는 목적은 그저 코드를 간단히 하는 정도일 테니,
이런 제약에 대해 너무 고민하지 않기를 바란다.
```
